[{
	"resource": "/c:/Users/Dell/OneDrive/Desktop/Student_OS/frontend/src/components/ui/calender.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'components'.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 11,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Dell/OneDrive/Desktop/Student_OS/frontend/src/components/ui/calender.tsx",
	"owner": "typescript",
	"code": "1136",
	"severity": 8,
	"message": "Property assignment expected.",
	"source": "ts",
	"startLineNumber": 1,
	"startColumn": 13,
	"endLineNumber": 1,
	"endColumn": 14,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Dell/OneDrive/Desktop/Student_OS/frontend/src/components/ui/calender.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ChevronLeft'.",
	"source": "ts",
	"startLineNumber": 4,
	"startColumn": 15,
	"endLineNumber": 4,
	"endColumn": 26,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Dell/OneDrive/Desktop/Student_OS/frontend/src/components/ui/calender.tsx",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'ChevronRight'.",
	"source": "ts",
	"startLineNumber": 6,
	"startColumn": 13,
	"endLineNumber": 6,
	"endColumn": 25,
	"modelVersionId": 3,
	"origin": "extHost1"
},{
	"resource": "/c:/Users/Dell/OneDrive/Desktop/Student_OS/frontend/src/components/ui/calender.tsx",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "Declaration or statement expected.",
	"source": "ts",
	"startLineNumber": 8,
	"startColumn": 2,
	"endLineNumber": 8,
	"endColumn": 3,
	"modelVersionId": 3,
	"origin": "extHost1"
}]